### ISSUE TITLE
The function of counter_map

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#1]
``[output_pred_coords_world = [v for i,v in enumerate(pred_coords_world) if v!=self.current_coord and self.counter_map[v[1],v[0]]<10](url)``

Hello, what is the function of counter_map? Why did he take the threshold 10?

**Comment by GuoxingYan** [comment]
Thank you for your team's open source work.

**Comment by TonyXuQAQ** [comment]
Hi Yan,

```counter_map``` is used to record how many times a pixel is visited by the agent(i.e., how many times the agent moves to a pixel). It is used to kill an infinite loop that randomly occurs. In our experiments, we observe that sometimes the agent keeps moving in a small region and cannot get out of it. Thus, we use ```counter_map``` to eliminate such infinite loops.

Under common circumstances, a pixel should not be visited by the agent more than 10 times. Thus, if a pixel is visited more than 10 times by the agent, we remove that pixel from the predicted vertices in the next step (i.e., $\hat{v}_{t+1}$), so that the agent will not consider such pixels and the infinite loop is killed.

**Comment by GuoxingYan** [comment]
> Hi Yan,
> 
> `counter_map` is used to record how many times a pixel is visited by the agent(i.e., how many times the agent moves to a pixel). It is used to kill an infinite loop that randomly occurs. In our experiments, we observe that sometimes the agent keeps moving in a small region and cannot get out of it. Thus, we use `counter_map` to eliminate such infinite loops.
> 
> Under common circumstances, a pixel should not be visited by the agent more than 10 times. Thus, if a pixel is visited more than 10 times by the agent, we remove that pixel from the predicted vertices in the next step (i.e., v^t+1), so that the agent will not consider such pixels and the infinite loop is killed.

I see. Thank you very much for your reply.
