### ISSUE TITLE
About RNGDet result

### ISSUE THREAD

**Issue by Dawn-bin** [TonyXuQAQ/RNGDetPlusPlus#10]
Hi, thanks for your wonderful work! I have run **RNGDet** on Cityscale testing set, but the results is lower than that report in the paper. I use the conda enviroment, instead of docker. Is there anything wrong? And I wonder which version of **torch** did you use? I not find in the [requirement.txt](https://github.com/TonyXuQAQ/RNGDetPlusPlus/blob/master/docker/requirement.txt).
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/17209/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/17209/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Prec. | Rec. | F1 | APLS
-- | -- | -- | --
86.01 | 68.57 | 76.13 | 63.758

</body>

</html>

**Comment by TonyXuQAQ** [comment]
Sorry that we uploaded the incorrect checkpoint and there are still some bugs in the code. We will try to fix them ASAP. Thanks for the reported issue.

**Comment by TonyXuQAQ** [comment]
Hi, sorry that we uploaded the incorrect checkpoints. We have re-upload correct ones and fixed several bugs in the code. Please pull the latest commit and re-download checkpoints for inference. Sorry for the caused inconvenience.

For RNGDet: "final_APLS": 0.6571125925925926

BTW, due to the randomness of RNGDet/RNGDet++ and the evaluation metrics, the actual scores might be slightly different from the number reported in the paper.

Should you have further questions, open an issue for discussion. Thanks.

**Comment by Dawn-bin** [comment]
Thanks for ur help! I have repeated the results.
