### ISSUE TITLE
About Evaluation Metrics

### ISSUE THREAD

**Issue by yuzhaoluone** [TonyXuQAQ/RNGDetPlusPlus#21]
Hello, I found that in the accuracy evaluation section, you mentioned in the RNGDet paper: "For a pixel in B∗, if there exists a pixel in ˆB and the Euclidean distance between them is smaller than δ, then this pixel is treated as correctly retrieved." I would like to ask how you implemented this accuracy evaluation code, is it done with a dilation-corrosion algorithm? Can you share the relevant code? Thanks.

**Comment by TonyXuQAQ** [comment]
Sorry for the late reply. 

After obtaining the graph, we first rasterize the graph into a binary image, or you can say a skeleton (the road has one-pixel width). 
<img width="40%" alt="image" src="https://user-images.githubusercontent.com/33851435/223297746-6e9a5a5d-3b42-489e-b10f-95d1289f2347.png">

After obtaining the skeletons of pred_graph and gt_graph, we can calculate the metric score based on pixels. This metric is used for validation in RNGDet++ due to its simplicity (code [here](https://github.com/TonyXuQAQ/RNGDetPlusPlus/blob/5b826387d9dc0b315905503f7ce4ad7c15af24f1/cityscale/main_train.py#L206)). During the inference of RNGDet++, we only used metrics proposed by Sat2Graph for evaluation, and this metics is not adopted.
