### ISSUE TITLE
Segmentation operations during training

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#8]
in agent.py
` for i in range(self.image_size//self.crop_size+1):
       for j in range(self.image_size//self.crop_size+1):`
This may affect the test speed. I understand that you can change crop_size to 1024 and directly output the output to reduce the running of the for statement. Excuse me, do I understand correctly?

In addition, in the preprocessing process of the training, the segmentation loss operation is performed on the whole image.

**Comment by GuoxingYan** [comment]
Whether multi-phase training is required, for example, training the segmented model first.

**Comment by GuoxingYan** [comment]
Whether the full image is used for training the segmentation network.

**Comment by TonyXuQAQ** [comment]
Hi Yan,

RNGDet and RNGDet++ are end-to-end trainable, and in our experiments, we directly train everything simultaneously. Thus multi-phase training is not needed. Since the whole network is trained together, we do not train an additional segmentation network for full image segmentation (or with ```crop_size``` as 1024). Instead, RNGDet and RNGDet++ train the segmentation maps of each cropped ROI (whose size is $128\times 128$ in our experiments),  thus in the inference period, we need to merge segmentation maps of each ROI into the global one. Even though doing so may affect the overall efficiency, to make the whole system simple and end-to-end trainable, we keep the current working pipeline.

**Comment by GuoxingYan** [comment]
I understand. Thank you very much for your reply.

**Comment by GuoxingYan** [comment]
> Hi Yan,
> 
> RNGDet and RNGDet++ are end-to-end trainable, and in our experiments, we directly train everything simultaneously. Thus multi-phase training is not needed. Since the whole network is trained together, we do not train an additional segmentation network for full image segmentation (or with `crop_size` as 1024). Instead, RNGDet and RNGDet++ train the segmentation maps of each cropped ROI (whose size is 128×128 in our experiments), thus in the inference period, we need to merge segmentation maps of each ROI into the global one. Even though doing so may affect the overall efficiency, to make the whole system simple and end-to-end trainable, we keep the current working pipeline.

I understand. Thank you very much for your reply.
