### ISSUE TITLE
about Training label calculation

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#9]
In Fig. 7. What is the significance of the intersection model? Why is the threshold set to 20 instead of 40 in this model?

I understand that in your paper, the starting point label of the intersection road is never the intersection point, but the point outside the intersection point 20. The penultimate point of the end is also the intersection.

**Comment by TonyXuQAQ** [comment]
Hi Yan,

Thanks for the question. It is unnecessary to be confused about this parameter $\tau'$. You could actually use other values here. In the implementation, we think that at road intersections what we actually need are some initial points for road segments, so we use a value (i.e., $\tau'$, 20 pixels in our paper) smaller than the maximum step size (i.e., $\tau$, 40 pixels). Smaller $\tau'$ should be a better option since if there are some errors, smaller $\tau'$ could restrict the error within an acceptable range so that it would be easier to correct them in subsequent steps.

You could try other values, and our model should not be much affected by this parameter.
